version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.4
    volumes:
      - acme:/letsencrypt
      - logs:/var/log
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - edge
      - socket-proxy
    configs:
      - source: traefik
        target: /etc/traefik/traefik.toml
      - source: dynamic
        target: /etc/traefik/dynamic.yml

configs:
  traefik:
    file: edge/traefik.$ENVmo.toml
  dynamic:
    file: edge/dynamic.yml

networks:
  edge:
    external: true
  socket-proxy:
    external: true

volumes:
  acme:
  logs: