version: "3.8"

services:
  db:
    image: mariadb
    volumes:
      - key_db:/var/lib/mysql
    env_file: keycloak/db/$ENV.env
    secrets:
      - db_password
    networks:
      - key-backend

  app:
    image: ghcr.io/zechmeister/agora/keycloak:latest
    env_file: keycloak/app/$ENV.env
    secrets:
      - db_password
      - keycloak_password
    networks:
      - edge
      - key-backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.keycloak.rule=Host(`nutzerinnenverwaltung.$HOST`)" 
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
        - "traefik.http.routers.keycloak.tls=true" 
        - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
        # Framing
        - "traefik.http.middlewares.keycloakFrame.headers.contentSecurityPolicy=frame-ancestors 'self' https://agora-oegd.de https://*.agora-oegd.de"
        - "traefik.http.routers.keycloak.middlewares=keycloakFrame"
        
secrets:
  db_password:
    file: ./keycloak/db/db_password.$ENV.txt
  keycloak_password:
    file: ./keycloak/app/keycloak_password.$ENV.txt


volumes:
  key_db:

networks:
  key-backend:
  edge:
    external: true
