version: "3.8"

services:
  db:
    image: mariadb
    volumes:
      - key_db:/var/lib/mysql
    env-file: keycloak/db/staging.env
    secrets:
      - db_password
    networks:
      - key-backend

  app:
    image: ghcr.io/zechmeister/agora/agora-keycloak:latest
    env-file: keycloak/app/staging.env
    secrets:
      - db_password
      - keycloak_password
    networks:
      - edge
      - key-backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.keycloak.rule=Host(`nutzerinnenverwaltung.agora-oegd.de`)" 
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
        - "traefik.http.routers.keycloak.tls=true" 
        - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
        # Framing
        - "traefik.http.middlewares.keycloakFrame.headers.contentSecurityPolicy=frame-ancestors https://agora-oegd.de"
        - "traefik.http.routers.keycloak.middlewares=keycloakFrame"
        
secrets:
  db_password:
    file: ./keycloak/secrets/db_password.staging.txt
  keycloak_password:
    file: ./keycloak/secrets/keycloak_password.staging.txt


volumes:
  key_db:

networks:
  key-backend:
  edge:
    external: true
