version: "3.8"

services:
  loki:
    image: grafana/loki:2.3.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.1.1
    networks:
      - loki
      - edge
    volumes:
      - grafana-data:/var/lib/grafana
    env_file: monitor/$ENV.env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`monitor.$HOST`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"

networks:
  loki:
  edge:
    external: true

volumes:
  loki-data:
  grafana-data: