[log]
	#filePath = "/var/log/traefik.log"
	format = "json"
	# level = "DEBUG"

[accessLog]
	#filePath = "/var/log/traefik_access.log"
	format = "json"
	bufferingSize = 100
	# uncommend for debugging
	# [accessLog.fields]
	# 	defaultMode = "keep"
	# 	[accessLog.fields.headers]
	# 		defaultMode = "keep"

[entryPoints]
	[entryPoints.web]
		address = ":80"

		[entryPoints.web.http]
		  [entryPoints.web.http.redirections]
		    [entryPoints.web.http.redirections.entryPoint]
		    	to = "websecure"
		    	scheme = "https"

	[entryPoints.websecure]
		address = ":443"
		# set forwardedHeaders if traefik sits behind another router/firewall
		#[entryPoints.websecure.forwardedHeaders]
		#	trustedIPs = ["99.99.99.99"]

[providers]
	[providers.docker]
		endpoint = "tcp://socket-proxy:2375"
		swarmMode = true
		watch = true
		exposedByDefault = false
		network = "edge"

	# middlewares
	[providers.file]
		filename = "/etc/traefik/dynamic.yml"

# Let's Encrypt 
[certificatesResolvers.myresolver.acme]
 email = "mail@example.com"
 storage = "letsencrypt/acme.json"
 [certificatesResolvers.myresolver.acme.httpChallenge]
   entryPoint = "web"