name: Agora-MediaWiki

on:
  push:
    paths:
      - "wiki/Dockerfile"
      - "wiki/agora.ini"
      - ".github/workflows/wiki-image.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  agora-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@main

      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          context: ./wiki
          push: true
          tags: ghcr.io/${{ github.repository }}/wiki:${{ github.run_number }}
      - name: Deploy to test
        # if: github.event.schedule == '0 0 * * *'
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://root@test.agora-oegd.de
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          args: stack deploy -c wiki.yml wiki --with-registry-auth
